---
language: node_js
node_js:
  - "6"

sudo: false
#dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

#before_install:
#  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
#  - npm install -g yarn

install:
  - "yarn add global bower"
  - "yarn install --prefer-offline"
  - "bower install"
